language: generic

sudo: required

services:
  - docker

before install:
  - docker build -t kyh0404/react-docker-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true kyh0404/react-docker-app  npm run test

after success:
  - docker build -t kyh0404/docker-frontend ./frontend
  - docker build -t kyh0404/docker-backend ./backend
  - docker build -t kyh0404/docker-nginx ./nginx

  - docker login -u "$DOCKER_HUB_ID" -p "$DOCKER_HUB_PASSWORD docker.iosword-stdin

  - docker push kyh0404/docker-frontend
  - docker push kyh0404/docker-backend
  - docker push kyh0404/docker-nginx
