language: generic

sudo: required

services:
  - docker

before install:
  - docker build -t kimyounghoon/react-docker-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true kimyounghoon/react-docker-app  npm run test

after success:
  - docker build -t kimyounghoon/docker-frontend ./frontend
  - docker build -t kimyounghoon/docker-backend ./backend
  - docker build -t kimyounghoon/docker-nginx ./nginx

  - docker login -u "$DOCKER_HUB_ID" -p "$DOCKER_HUB_PASSWORD docker.io

  - docker push kimyounghoon/docker-frontend
  - docker push kimyounghoon/docker-backend
  - docker push kimyounghoon/docker-nginx
