language: generic

sudo: required

services:
  - docker

before install:
  - docker build -t kyh0404/react-docker-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true kyh0404/react-docker-app  npm run test

after success:
  - docker build -t kyh0404/docker-frontend ./frontend
  - docker build -t kyh0404/docker-backend ./backend
  - docker build -t kyh0404/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push kyh0404/docker-frontend
  - docker push kyh0404/docker-backend
  - docker push kyh0404/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-392755599004
  bucket_path: "Docker-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
