version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: backend_app
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: MYSQL_HOST
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: kimyounghoon77
      MYSQL_DATABASE: app_data
      MYSQL_PORT: 3306
